# This file was autogenerated. DO NOT EDIT!
{
  version = "v2.10.0";
  cfVersion = "v0.2.1";
  ddnsVersion = "v0.0.0-20250419190939-bc90ac0e772f";
  vendorHash = "sha256-E6XYZB+dlAsxPMj+jLWFN4Vkp9bPzPCJBw6frdwZg3o=";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.10.0";
    hash = "sha256-us1TnszA/10OMVSDsNvzRb6mcM4eMR3pQ5EF4ggA958=";
  };
}
